platform :ios, '10.0'

target 'dev' do
  #RN Core Code
  pod 'React', :path => '../../../../../../node_modules/react-native'
  pod 'React-Core', :path => '../../../../../../node_modules/react-native/'
  
  #RN
  pod 'FBReactNativeSpec', :path => '../../../../../../node_modules/react-native/React/FBReactNativeSpec'
  pod 'React-CoreModules', :path => '../../../../../../node_modules/react-native/React/CoreModules'
  
  #RN Common
  pod 'ReactCommon', :path => '../../../../../../node_modules/react-native/ReactCommon'
  pod 'React-cxxreact', :path => '../../../../../../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../../../../../../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../../../../../../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../../../../../../node_modules/react-native/ReactCommon/jsinspector'
  pod 'React-perflogger', :path => '../../../../../../node_modules/react-native/ReactCommon/reactperflogger'
  pod 'React-callinvoker', :path => '../../../../../../node_modules/react-native/ReactCommon/callinvoker'
  pod 'React-runtimeexecutor', :path => '../../../../../../node_modules/react-native/ReactCommon/runtimeexecutor'
  pod 'Yoga', :path => '../../../../../../node_modules/react-native/ReactCommon/yoga'
  
  #RN Official Lib
  pod 'React-RCTActionSheet', :path => '../../../../../../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../../../../../../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../../../../../../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../../../../../../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../../../../../../node_modules/react-native/Libraries/LinkingIOS'
  pod 'RCTTypeSafety', :path => "../../../../../../node_modules/react-native/Libraries/TypeSafety"
  pod 'React-RCTNetwork', :path => '../../../../../../node_modules/react-native/Libraries/Network'
  pod 'RCTRequired', :path => "../../../../../../node_modules/react-native/Libraries/RCTRequired"
  pod 'React-RCTSettings', :path => '../../../../../../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../../../../../../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../../../../../../node_modules/react-native/Libraries/Vibration'
  pod 'FBLazyVector', :path => '../../../../../../node_modules/react-native/Libraries/FBLazyVector'
  
  #RN Third Party
  pod 'RCT-Folly', :podspec => '../../../../../../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec'

  #Plugin
  pod 'RCReactNativeIm', :path => '../'
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end



